# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
PROJECT_DIR       = /home/babar/Documents/Bicopter/Arduino_Hover/Arduino_Hover
USER_LIB_PATH    =  /home/babar/src/Arduino/libraries
BOARD_TAG    = nano328
ARDUINO_LIBS += RF24-master SPI Wire ADXL345_library Servo ITG3200_library EEPROMEx
# GPS pin Affichage


#MONITOR_PORT = /dev/ttyUSB0
#MONITOR_BAUDRATE  = 115200
include /usr/share/arduino/Arduino.mk